export type { Box, Rect, Region, PageFactory, GateSummary } from './types';
export { overlaps, findOverlaps, findOverlapsWithin, canvasBoxToPage, controlName } from './boxes';
export type { Band, CanvasFrame, ControlIdentity } from './boxes';
export { PHONE_DEVICE, DESKTOP_DEVICE, PHONE_SIZE, DESKTOP_SIZE, deviceDescriptor, phone, desktop, gameProjects } from './devices';
export type { Size, GameProject, GameProjectsOptions } from './devices';
export { RELAYOUT_TIMEOUT_MS, armVisibleHeight, shrinkVisibleHeight } from './visible-height';
export type { ShrinkOptions } from './visible-height';
export { GAME_SHELL_HEIGHT_VAR, DEFAULT_CANVAS_SELECTOR, FIT_TIMEOUT_MS, CANVAS_TIMEOUT_MS, expectFitTo, expectCanvasHeight, expectCanvasInside } from './fit';
export type { FitOptions, CanvasOptions } from './fit';
export { CONTROL_SELECTOR, domControls } from './dom-controls';
export { EXACT, ANTI_ALIAS_TOLERANCE, countDiff } from './pixel-diff-math';
export type { DiffResult } from './pixel-diff-math';
export { diffPngs, regionDiff } from './pixel-diff';
export type { DiffOptions, RegionInput } from './pixel-diff';
export { MIN_TARGET_PX, MAX_REPORTED, renderFindings, renderRouteAudit, routeProblems, summariseTouchTargets } from './touch-report';
export type { TargetFinding, TargetProbeFunnel, TargetAudit, RouteAudit } from './touch-report';
export { auditTouchTargets, auditRoute, expectTouchTargetsAcrossRoutes, expectTouchTargets } from './touch-targets';
export { toOverflowReading, renderOverflow, summariseOverflow } from './overflow-report';
export type { OverflowMetrics, OverflowReading, RouteOverflow } from './overflow-report';
export { readHorizontalOverflow, measureHorizontalOverflow, horizontalOverflowPx, expectNoHorizontalOverflowAcrossRoutes, expectNoHorizontalOverflow } from './overflow';
